### PR TITLE
Fix/supporters undefined

### LINKED ISSUE #64: FIx supporters showing as undefined when clicking category and clicking search on Admin page

### PR DESCRIPTION
**Pull request by ShaunaMyers**
# Description

- Fix bug about supporters being undefined
- Remove categorySelected from state and instead declare categorySelected as a variable (no more async issues)
- Style Admin inputs and labels for mobile responsiveness

Closes #64 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Developer Tools
- [x] Live Site
- [ ] Cypress

## Checklist:

- [x] My code follows Turing's guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have generated no new error messages

### CODE REVIEW

File: src/components/Admin/Admin.js [hunk 1]
```diff
@@ -55,7 +56,9 @@ const Admin = () => {
     const assignCategorySelected = () => {
         const checkboxes = [otherChecked, organizingChecked, deliveryChecked, handiworkChecked, transportationChecked, foodPrepChecked];
         checkboxes.forEach((checkbox, index) => {
-            checkbox && setCategorySelected(index + 1)
+            if (checkbox) {
+                categorySelected = index + 1;
```
Comment (novaraptur) [inline src/components/Admin/Admin.js:60]: Nice! Smooth way of handling that!

**Review by novaraptur — APPROVED** [review]
