### PR TITLE
Fix/a tag warning

### LINKED ISSUE #61: Fix warning about href missing on <a> tag
- [ ] change <a> tag to button and remove button styling so it appears to be a link (with underline text-decoration)

### PR DESCRIPTION
**Pull request by ShaunaMyers**
# Description

- Change <a> tag to button element and remove default button styling

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring

Closes #61 

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Developer Tools
- [x] Live Site
- [ ] Cypress

## Checklist:

- [x] My code follows Turing's guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have generated no new error messages

### CODE REVIEW

File: src/components/Search/Search.js [hunk 1]
```diff
@@ -107,7 +107,7 @@ const Search = ({ handleSearchSubmit, handleViewAllNeeds, searchResults }) => {
                     </div>
                 <button onClick={onSearchSubmit} className="search-button">Search</button>
                 {(successfulSearch || !!searchResults.length) && 
-                <a onClick={onViewAllNeeds} className="see-all-link">See All Needs</a>
+                <button onClick={onViewAllNeeds} className="see-all-button">See All Needs</button>
```
Comment (novaraptur) [inline src/components/Search/Search.js:110]: Nice, good catch! Simple fix is super nice.

**Review by novaraptur — APPROVED** [review]
